//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revista_Capacitacion
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CAPACITACIONEntities7 : DbContext
    {
        public CAPACITACIONEntities7()
            : base("name=CAPACITACIONEntities7")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<M_CATEGORIAS> M_CATEGORIAS { get; set; }
        public virtual DbSet<REVISTA> REVISTAS { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
