//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revista_Capacitacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class REVISTAS
    {
        public int ID_REV { get; set; }
        public string TITULO_REV { get; set; }
        public string CB { get; set; }
        public Nullable<System.DateTime> FECHA_CIRCULACION { get; set; }
        public Nullable<int> ID_CAT { get; set; }
        public Nullable<System.DateTime> ROW_CREATE { get; set; }
        public Nullable<double> PRECIO { get; set; }

        public List<REVISTAS> ShowallCustomer { get; set; }

        public virtual M_CATEGORIAS M_CATEGORIAS { get; set; }
    }
}
